eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
name:
  value: arjay
spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0

keyStore:
  path: keystore.jks
  password: password


aws:
  s3:
    access:
      key: AKIAT4GVRMTPCE7WS4MA
    secret:
      key: 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
    region: eu-north-1
    bucket: arjay-fileupload