server:
  port: 8070
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/event
    username: arjay
    password: arjay
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      group-id: eventGroup
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: eventConfirmation:com.rjproj.memberapp.eventconfirmation.model.EventConfirmation

application:
  config:
    member-url: http://localhost:8050/api/v1/member
    organization-url: http://localhost:8090/api/v1/organization

#    member-url: http://localhost:8222/api/v1/member
#    organization-url: http://localhost:8222/api/v1/organization