server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: organization-service
          uri: lb:http://ORGANIZATION-SERVICE
          predicates:
            - Path=/api/v1/organization/**
        - id: member-service
          uri: lb:http://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/member/**
        - id: membership-service
          uri: lb:http://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/membership/**
        - id: membership-type-service
          uri: lb:http://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/membership-type/**
        - id: authentication-service
          uri: lb:http://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: event-service
          uri: lb:http://EVENT-SERVICE
          predicates:
            - Path=/api/v1/event/**
        - id: event-confirmation-service
          uri: lb:http://EVENT-SERVICE
          predicates:
            - Path=/api/v1/event-confirmation/**


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/  # Eureka server URL
#    registerWithEureka: true  # Register this service in Eureka
#    fetchRegistry: true  # Fetch service registry from Eureka
#  instance:
#    preferIpAddress: true  #