spring:
  data:
    mongodb:
      username: arjay
      password: arjay
      host: localhost
      port: 27017
      database: organization
      authentication-database: admin


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8090


application:
  config:
    membership-type-url: http://localhost:8222/api/v1/membership-type
    membership-url: http://localhost:8222/api/v1/membership
    member-url: http://localhost:8222/api/v1/member


#  feign.compression.response.enabled=true
#  feign.compression.response.useGzipDecoder=true