spring:
  data:
    mongodb:
      username: arjay
      password: arjay
      host: localhost
      port: 27017
      database: organization
      authentication-database: admin

server:
  port: 8090