spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: organization-service

aws:
  s3:
    access:
      key: AKIAT4GVRMTPCE7WS4MA
    secret:
      key: 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
    region: eu-north-1
    bucket: arjay-fileupload