server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

aws:
  s3:
    access:
      key: AKIAT4GVRMTPBTFGNH77
    secret:
      key: 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
    region: eu-north-1
    bucket: arjay-fileupload
