server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

aws:
  s3:
    access:
      key: AKIAT4GVRMTPCE7WS4MA
    secret:
      key: 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
    region: eu-north-1
    bucket: arjay-fileupload